### ISSUE TITLE
Passing an invalid index to `OwnedFace::from_vec` returns a valid font

### ISSUE THREAD

**Issue by Pietrek14** [alexheretic/owned-ttf-parser#10]
If you pass an index that's bigger than the number of fonts available, it still returns a valid font. You can see that by changing the index in the `owned_ttf` test `move_and_use` to any other number than 0 - it will still pass.

**Comment by alexheretic** [comment]
I assume this is the behaviour of upstream [ttf-parser](https://github.com/RazrFalcon/ttf-parser) though right?

Maybe worth raising an issue there as I would have expected a `FaceParsingError::FaceIndexOutOfBounds` for this case.

**Comment by Pietrek14** [comment]
It seems to be working alright now.
