### ISSUE TITLE
New ttf-parser versions released

### ISSUE THREAD

**Issue by torokati44** [alexheretic/owned-ttf-parser#17]
This is just a polite ping that there were two new `ttf-parser` versions released recently, and we'd love to update to them, with a matching `owned-ttf-parser` release. If you could use any assistance in getting a release out, let me know.

**Comment by alexheretic** [comment]
Upstream 0.23 was published a couple of hours ago, I'll publish a new version this crate soon. 

You say "two new versions" but 0.22 was published a few days ago. Do you mean something else?

**Comment by torokati44** [comment]
Yes I meant 0.22 and 0.23. I failed to check whether you already published `owned-ttf-parser` `v0.22`, sorry. But you did! Really appreciate the quick reaction, thank you! ☺️
