### ISSUE TITLE
Consider supporting rustc 1.36.0

### ISSUE THREAD

**Issue by jrmuizel** [alexheretic/owned-ttf-parser#2]
https://github.com/38/plotters is currently blocked from upgrading to rusttype 0.9 because it has a MSRV of 1.36.0. See https://github.com/38/plotters/pull/149

**Comment by alexheretic** [comment]
I maintain all my crates with using the latest stable rust, see [msrv policy](https://gist.github.com/alexheretic/d1e98d8433b602e57f5d0a9637927e0c).

I don't support using old compilers for new versions.
