### ISSUE TITLE
Clarify against owning-ref

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [alexheretic/owned-ttf-parser#3]
It'd be nice to clarify the advantage of this crate over owning-ref :)

**Comment by alexheretic** [comment]
I assume you mean using owning-ref + ttf-parser to provide an owned version.

In general, if you're using a self-ref helper and it works for you go for it. 

When I was solving the issue this crate exists to solve I found they did not work for me, or required `unsafe` which totally defeats the point of using a self-ref helper (other than `Pin` itself).

**Comment by Matthias-Fauconneau** [comment]
Ok, I thought I only had to unsafe because of mmap.
So, you hide the unsafe, and since you have to unsafe anyway, you also do the self ref with your own code.
