### ISSUE TITLE
Making some internal fields public.

### ISSUE THREAD

**Issue by wdanilo** [alexheretic/owned-ttf-parser#6]
Hi! 
I'd like to access the information on where the `glyf::Table` data starts and where it ends. I understand that I could do it by accessing the `glyf::Table::data`. Unfortunately, this field is `pub(crate)` only. Would it be possible to make it fully public, please? :)

**Comment by alexheretic** [comment]
I think you should raise this at [ttf-parser](https://github.com/RazrFalcon/ttf-parser) this repo just provides owned data support on top of that crate.

**Comment by wdanilo** [comment]
Oh, you are right. I was planning to raise it there, but somehow I probably switched my tabs. Thanks! :)
