### ISSUE TITLE
Allowing accessing `&[u8]` data from `OwnedFace` and deconstructing it to `Vec<u8>`.

### ISSUE THREAD

**Issue by wdanilo** [alexheretic/owned-ttf-parser#7]
Hi! I have 2 small API requests: 
1. Would it be possible to add a method providing users of this library access to slice of the data stored in `OwnedFace` (`&[u8]`)?
2. Would it be possible to add a method that takes the ownership of `OwnedFace` and returns the internal `Vec<u8>`? 

I described my exact use case in another issue on the [ttf-parser repo](https://github.com/RazrFalcon/ttf-parser/issues/103). In order to keep this issue short, I'm just pasting a link there :)

**Comment by alexheretic** [comment]
Yes I think having those feature makes sense.

**Comment by wdanilo** [comment]
@alexheretic thanks a lot! Do you want me to create PR? These are super small changes, so maybe no PR is needed, but if you want, I'd be glad to do it.

**Comment by alexheretic** [comment]
Np I can add it :) 1323cd5008d3666b87e3d5a8237a549605814d80

I'll release `0.15.1` towards the end of the week.

**Comment by wdanilo** [comment]
I'm speechless how fast this issue was resolved! Thanks thousand times!

**Comment by alexheretic** [comment]
I've released `0.15.1`
